insert into  THE_RIGHT_JOIN.Rol (rol_name, rol_habilitado)
values ('Cliente', 1)
insert into  THE_RIGHT_JOIN.Rol (rol_name, rol_habilitado)
values ('Proveedor', 1)
insert into  THE_RIGHT_JOIN.Rol (rol_name, rol_habilitado)
values ('Admnistrador', 1)